name: unav
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  # ===== Basic Environment =====
  - python=3.10
  - pip
  - setuptools
  - wheel

  # ===== Scientific Computing =====
  - numpy=1.26.4
  - scipy=1.15.3
  - pandas=2.2.3
  - h5py=3.13.0

  # ===== Machine/Deep Learning =====
  - pytorch
  - torchvision
  - xformers
  - open3d
  - kornia

  # ===== Data Processing & Visualization =====
  - scikit-learn=1.6.1
  - scikit-image=0.25.2
  - pillow=11.2.1
  - matplotlib=3.10.3
  - tqdm=4.67.1
  - prettytable=3.11.0
  - networkx=3.4.2
  - einops=0.8.1
  - joblib=1.5.1

  # ===== Backend & Development =====
  - fastapi
  - uvicorn
  - sqlalchemy

  # ===== Others =====
  - yaml
  - pyyaml
  - cryptography

  # ===== Additional pip dependencies =====
  - pip:
      - einops==0.8.1
      - faiss-gpu-cu12==1.11.0
      - fast-pytorch-kmeans==0.2.2
      - flask==3.0.3
      - h5py==3.13.0
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - PyJWT>=2.0.0
      - kornia==0.8.1
      - lazy-loader==0.4
      - matplotlib==3.10.3
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - pandas==2.2.3
      - passlib==1.7.4
      - pillow==11.2.1
      - poselib==2.0.4
      - pytorch-lightning==2.5.1.post0
      - pytorch-metric-learning==2.8.1
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - shapely==2.1.1
      - sqlalchemy==2.0.41
      - timm==1.0.15
      - tqdm==4.67.1
      - transformers==4.52.4
      - wandb==0.20.0
      - xformers==0.0.30

# ===== Usage =====
# 1. Run `conda env create -f environment.yaml` to create the environment.
# 2. To update, use `conda env update -f environment.yaml`.
# 3. Make sure the correct CUDA drivers are installed for GPU packages.
# 4. Use conda for most packages, pip only for those unavailable in conda.
